import Head from 'next/head'
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import HomeIcon from '@mui/icons-material/Home';
import Link from 'next/link';
import Tooltip, { tooltipClasses } from '@mui/material/Tooltip'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router';
import { useEffect } from 'react';

import { useRecoilValue } from 'recoil';
import userState from '../Recoil/userState';


export default function Layout({ children, home = false }) {

    const user = useRecoilValue(userState)
    const router = useRouter()
    const ruta = router.pathname


    useEffect(() => {
        if (!user.logeado) {
            router.push('/')
        }
    }, [user])

    return (
        <>

            <Head>
                <title>Programa VMC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css' />
            </Head>

            <AppBar position="static" sx={{ background: "#5b3c88", position:'sticky', top:0, zIndex:1000 }}>
                <Toolbar sx={{width:'100%', maxWidth:'1200px', m:'0 auto'}} >
                    
                    <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                        {ruta == '/matriculados' && 'Matriculados'}
                        {ruta == '/asignaciones' && 'Asignaciones'}
                    </Typography>

                    {ruta != '/asignaciones' &&

                        <Tooltip title="Volver al inicio" arrow placement='left'>
                            <IconButton onClick={() => router.push("/asignaciones")} sx={{ width: "30px", height: "30px" }}>
                                <i className="fi fi-rr-home" style={{ color: "white", fontSize: "15px" }} />
                            </IconButton>
                        </Tooltip>

                    }
                </Toolbar>
            </AppBar>

            <main>{children}</main>

            
        </>
    )
}